name: Node CI

on: [push]
env:
  FORCE_COLOR: 2
jobs:
  test:
    name: v${{ matrix.node }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - name: Build and run tests
      run: |
        npm run build --if-present
        npm test
    - name: Run linter
      run: |
        npm run lint --if-present
